name: Update Lexicons

on:
# TODO: Automate lexicon update process
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-lexicons:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Clone ATProto Repository
        uses: actions/checkout@v3
        with:
          repository: bluesky-social/atproto
          path: tmp-atproto

      - name: Overwrite Lexicons
        run: |
          rm -rf lexicons/schemas
          cp -R tmp-atproto/lexicons lexicons/schemas

      - name: Get Changed Files
        uses: tj-actions/verify-changed-files@v20
        id: changed-files

      - name: List Changed Files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $CHANGED_FILES"

      - name: Smoke Test
        if: steps.changed-files.outputs.files_changed == 'true'
        run: ./gradlew clean apiDump :app:desktop:assemble --no-daemon --stacktrace

      - uses: actions-ecosystem/action-get-latest-tag@v1
        if: steps.changed-files.outputs.files_changed == 'true'
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        if: steps.changed-files.outputs.files_changed == 'true'
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - name: Prepare Release Files
        if: steps.changed-files.outputs.files_changed == 'true'
        run: ./scripts/bump_version.sh ${{ steps.bump-semver.outputs.new_version }}

      - name: Dry Run - Get Changed Files
        uses: tj-actions/verify-changed-files@v20
        id: all-changed-files

      - name: Dry Run - List Changed Files
        env:
          ALL_CHANGED_FILES: ${{ steps.all-changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $ALL_CHANGED_FILES"

#      - name: Commit Changes
#        uses: stefanzweifel/git-auto-commit-action@v4
#        if: steps.changed-files.outputs.files_changed == 'true'
#        with:
#          commit_message: [${{ steps.bump-semver.outputs.new_version }}] Update lexicons from atproto
#          tagging_message: ${{ steps.bump-semver.outputs.new_version }}
